[package]
name = "rust_bpe_tokenizer_py"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_bpe_tokenizer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }

[dependencies.rust_bpe_tokenizer]
path = ".."